# Generated by Django 5.2.4 on 2025-08-07 15:02

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaveDate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this Save the Date invitation.', primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Main title of the event.', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('event_subtitle', models.CharField(blank=True, help_text='Optional subtitle for the event.', max_length=255, null=True)),
                ('event_summary', models.TextField(help_text='A short description or summary of the event.', validators=[django.core.validators.MinLengthValidator(10)])),
                ('event_date', models.DateField(help_text='The calendar date of the event.')),
                ('event_times', models.JSONField(blank=True, default=dict, help_text='Array of event times, each with label and time in 24-hour format.')),
                ('event_venue', models.CharField(help_text='Venue name, e.g., Grand Ballroom.', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('event_address', models.CharField(help_text='Street address of the venue.', max_length=255, validators=[django.core.validators.MinLengthValidator(3)])),
                ('event_city', models.CharField(help_text='City where the event takes place.', max_length=100, validators=[django.core.validators.MinLengthValidator(2)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
