# Generated by Django 5.2.4 on 2025-08-07 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savedate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedate',
            name='event_date',
        ),
    ]
